import XCTest
@testable import Freedom

/// Verifies the manifest canonicalization + EIP-191 recovery against golden
/// vectors generated by freedom-adblock-service's own signing code
/// (`canonicalManifestForSigning` / `signManifest`), plus a manifest captured
/// live from the mainnet feed. Byte-identical canonicalization across JS and
/// Swift is the load-bearing cross-repo contract — these vectors are the
/// proof.
final class AdblockUpdateManifestTests: XCTestCase {
    private struct Vectors: Decodable {
        let signerAddress: String
        let canonical: String
        let sig: String
        enum CodingKeys: String, CodingKey {
            case signerAddress = "signer_address"
            case canonical
            case sig
        }
    }

    private func fixtureData(_ name: String) throws -> Data {
        let bundle = Bundle(for: Self.self)
        guard let url = bundle.url(forResource: name, withExtension: "json") else {
            throw XCTSkip("fixture \(name).json not bundled")
        }
        return try Data(contentsOf: url)
    }

    private func vectors() throws -> (Vectors, payload: Data) {
        let data = try fixtureData("adblock-manifest-vectors")
        let vectors = try JSONDecoder().decode(Vectors.self, from: data)
        // The pretty-printed manifest (with sig) as the on-feed payload.
        let full = try JSONSerialization.jsonObject(with: data) as! [String: Any]
        let manifest = full["manifest_pretty"]!
        let payload = try JSONSerialization.data(withJSONObject: manifest)
        return (vectors, payload)
    }

    // MARK: - Canonicalization parity

    func testCanonicalBytesMatchPublisher() throws {
        let (vectors, payload) = try vectors()
        let canonical = try AdblockUpdateManifest.canonicalBytes(payload: payload)
        XCTAssertEqual(
            String(decoding: canonical, as: UTF8.self),
            vectors.canonical,
            "Swift canonicalization must be byte-identical to JS JSON.stringify(sortDeep(manifest))"
        )
    }

    func testRecoverSignerMatchesPublisherKey() throws {
        let (vectors, payload) = try vectors()
        let canonical = try AdblockUpdateManifest.canonicalBytes(payload: payload)
        let recovered = try AdblockUpdateManifest.recoverSigner(canonical: canonical, sig: vectors.sig)
        XCTAssertEqual(recovered, vectors.signerAddress.lowercased())
    }

    // MARK: - verify() pipeline

    func testVerifyAcceptsGoldenManifest() throws {
        let (vectors, payload) = try vectors()
        let manifest = try AdblockUpdateManifest.verify(
            payload: payload, sigAddress: vectors.signerAddress, appliedVersion: 6
        )
        XCTAssertEqual(manifest.version, 7)
        XCTAssertEqual(manifest.platforms.ios.lists.first?.shards.count, 2)
        XCTAssertEqual(manifest.desktopList(id: "easylist")?.title, "EasyList")
    }

    func testVerifyRejectsDowngrade() throws {
        let (vectors, payload) = try vectors()
        XCTAssertThrowsError(
            try AdblockUpdateManifest.verify(
                payload: payload, sigAddress: vectors.signerAddress, appliedVersion: 7
            )
        ) { error in
            XCTAssertEqual(
                error as? AdblockManifestError,
                .notNewer(version: 7, applied: 7)
            )
        }
    }

    func testVerifyRejectsWrongSigner() throws {
        let (_, payload) = try vectors()
        XCTAssertThrowsError(
            try AdblockUpdateManifest.verify(
                payload: payload,
                sigAddress: "0xf6aa84e06Ed0C5fF6DD707fba16F0c1BA459FCE0",
                appliedVersion: nil
            )
        ) { error in
            guard case .signerMismatch = error as? AdblockManifestError else {
                return XCTFail("expected signerMismatch, got \(error)")
            }
        }
    }

    func testVerifyRejectsTamperedPayload() throws {
        let (vectors, payload) = try vectors()
        // Flip the version — the sig no longer covers the canonical bytes.
        var object = try JSONSerialization.jsonObject(with: payload) as! [String: Any]
        object["version"] = 8
        let tampered = try JSONSerialization.data(withJSONObject: object)
        XCTAssertThrowsError(
            try AdblockUpdateManifest.verify(
                payload: tampered, sigAddress: vectors.signerAddress, appliedVersion: nil
            )
        ) { error in
            guard case .signerMismatch = error as? AdblockManifestError else {
                return XCTFail("expected signerMismatch, got \(error)")
            }
        }
    }

    func testVerifyRejectsBadSchema() throws {
        let (vectors, payload) = try vectors()
        var object = try JSONSerialization.jsonObject(with: payload) as! [String: Any]
        object["schema"] = 2
        let mutated = try JSONSerialization.data(withJSONObject: object)
        XCTAssertThrowsError(
            try AdblockUpdateManifest.verify(
                payload: mutated, sigAddress: vectors.signerAddress, appliedVersion: nil
            )
        ) { error in
            XCTAssertEqual(error as? AdblockManifestError, .badSchema(2))
        }
    }

    // MARK: - Live manifest (captured from the mainnet feed)

    func testLiveManifestVerifies() throws {
        let payload = try fixtureData("adblock-live-manifest-v4")
        let manifest = try AdblockUpdateManifest.verify(
            payload: payload,
            sigAddress: "0xf6aa84e06Ed0C5fF6DD707fba16F0c1BA459FCE0",
            appliedVersion: 3
        )
        XCTAssertEqual(manifest.version, 4)
        XCTAssertEqual(manifest.platforms.ios.lists.count, 4)
        XCTAssertFalse(manifest.platforms.ios.lists.flatMap(\.shards).isEmpty)
    }

    // MARK: - Feed topic contract

    func testFeedTopicHexMatchesBeeJs() {
        // keccak256("freedom/adblock/lists/v1") — bee-js Topic.fromString parity,
        // captured from the publisher run.
        XCTAssertEqual(
            AdblockUpdateFeed.feedTopicHex,
            "96741f799248290fa67445649f572f1c773238c1f07e2e98643c625370f9bc15"
        )
    }
}
