import XCTest
@testable import Freedom

/// The update pipeline against stubbed IO: a signed v5 manifest + blob set
/// generated by the publisher's own signing code
/// (`Fixtures/adblock-update-fixture.json`). No node, no WebKit — compile and
/// activate are recorded by stubs.
@MainActor
final class AdblockUpdateServiceTests: XCTestCase {
    private struct Fixture: Decodable {
        let signerAddress: String
        let manifestPayload: String
        let blobs: [String: String]
        enum CodingKeys: String, CodingKey {
            case signerAddress = "signer_address"
            case manifestPayload = "manifest_payload"
            case blobs
        }
    }

    private var fixture: Fixture!
    private var root: URL!

    override func setUpWithError() throws {
        let bundle = Bundle(for: Self.self)
        guard let url = bundle.url(forResource: "adblock-update-fixture", withExtension: "json") else {
            throw XCTSkip("fixture not bundled")
        }
        fixture = try JSONDecoder().decode(Fixture.self, from: Data(contentsOf: url))
        root = FileManager.default.temporaryDirectory
            .appendingPathComponent("adblock-update-tests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
    }

    override func tearDownWithError() throws {
        try? FileManager.default.removeItem(at: root)
        UserDefaults.standard.removeObject(forKey: "adblock.update.lastCheck")
    }

    /// Stubbed IO. Records precompile/activate calls and downloaded refs.
    private final class Recorder {
        var downloadedRefs: [String] = []
        var precompiled: [(version: Int, dir: URL)] = []
        var activated: [(version: Int, dir: URL)] = []
        var precompileError: Error?
    }

    private func makeIO(recorder: Recorder, payload: Data? = nil) -> AdblockUpdateService.IO {
        let payloadData = payload ?? Data(fixture.manifestPayload.utf8)
        let blobs = fixture.blobs
        return AdblockUpdateService.IO(
            readFeed: { payloadData },
            downloadBlob: { ref in
                recorder.downloadedRefs.append(ref)
                guard let blob = blobs[ref] else {
                    throw AdblockManifestError.malformed("unknown ref \(ref)")
                }
                return Data(blob.utf8)
            },
            rootDir: root,
            sigAddress: fixture.signerAddress,
            trustConfigured: true,
            precompile: { _, dir, version in
                if let error = recorder.precompileError { throw error }
                recorder.precompiled.append((version, dir))
            },
            activate: { version, dir in
                recorder.activated.append((version, dir))
            }
        )
    }

    private func makeService(io: AdblockUpdateService.IO) -> AdblockUpdateService {
        AdblockUpdateService(settings: SettingsStore(), io: io)
    }

    // MARK: - Happy path

    func testAppliesUpdateEndToEnd() async throws {
        let recorder = Recorder()
        let service = makeService(io: makeIO(recorder: recorder))

        let outcome = await service.runOnce()

        XCTAssertEqual(outcome, .applied(version: 5))
        XCTAssertEqual(recorder.downloadedRefs.count, 3, "all three shards downloaded")
        XCTAssertEqual(recorder.precompiled.map(\.version), [5])
        XCTAssertEqual(recorder.activated.map(\.version), [5])

        let updated = root.appendingPathComponent("updated")
        XCTAssertTrue(FileManager.default.fileExists(atPath: updated.appendingPathComponent("easylist-1.json").path))
        XCTAssertTrue(FileManager.default.fileExists(atPath: updated.appendingPathComponent("metadata.json").path))
        XCTAssertEqual(AdblockUpdateService.appliedState(rootDir: root)?.feedVersion, 5)

        // Precompile ran against the staging dir, not the final one.
        XCTAssertTrue(recorder.precompiled[0].dir.lastPathComponent == "updated.next")

        // The derived metadata decodes through the bundled-manifest path.
        if case .updated(let feedVersion, let dir) = AdblockUpdateService.currentSource(rootDir: root) {
            XCTAssertEqual(feedVersion, 5)
            XCTAssertEqual(dir.lastPathComponent, "updated")
        } else {
            XCTFail("expected .updated source after apply")
        }
    }

    func testSecondRunIsNotNewer() async throws {
        let recorder = Recorder()
        let service = makeService(io: makeIO(recorder: recorder))
        _ = await service.runOnce()
        recorder.downloadedRefs = []

        let outcome = await service.runOnce()

        XCTAssertEqual(outcome, .notNewer(version: 5))
        XCTAssertTrue(recorder.downloadedRefs.isEmpty, "nothing re-downloaded")
        XCTAssertEqual(recorder.activated.map(\.version), [5], "no second activation")
    }

    // MARK: - Failure modes

    func testTamperedBlobAbortsWithoutTouchingActive() async throws {
        var fixtureBlobs = fixture.blobs
        // Corrupt one blob — sha256 check must fail.
        let firstRef = fixtureBlobs.keys.sorted().first!
        fixtureBlobs[firstRef] = "tampered"
        let recorder = Recorder()
        var io = makeIO(recorder: recorder)
        io.downloadBlob = { ref in
            guard let blob = fixtureBlobs[ref] else { throw AdblockManifestError.malformed("no ref") }
            return Data(blob.utf8)
        }
        let service = makeService(io: io)

        let outcome = await service.runOnce()

        guard case .failed = outcome else { return XCTFail("expected .failed, got \(outcome)") }
        XCTAssertNil(AdblockUpdateService.appliedState(rootDir: root), "no update applied")
        XCTAssertTrue(recorder.activated.isEmpty)
        XCTAssertFalse(
            FileManager.default.fileExists(atPath: root.appendingPathComponent("updated.next").path),
            "staging cleaned up"
        )
    }

    func testPrecompileFailureLeavesPreviousUpdateActive() async throws {
        // First, apply v5 normally.
        let recorder = Recorder()
        let service = makeService(io: makeIO(recorder: recorder))
        _ = await service.runOnce()

        // Now feed a "v6" (reuse payload with bumped version → sig breaks, so
        // instead simulate compile failure on a fresh root with v5).
        let root2 = FileManager.default.temporaryDirectory
            .appendingPathComponent("adblock-update-tests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: root2, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: root2) }

        let failing = Recorder()
        failing.precompileError = AdblockError.compileFailed("boom")
        var io = makeIO(recorder: failing)
        io.rootDir = root2
        let service2 = makeService(io: io)

        let outcome = await service2.runOnce()

        guard case .failed = outcome else { return XCTFail("expected .failed, got \(outcome)") }
        XCTAssertNil(AdblockUpdateService.appliedState(rootDir: root2))
        XCTAssertTrue(failing.activated.isEmpty)
        XCTAssertEqual(AdblockUpdateService.currentSource(rootDir: root2).identifierPrefix, "freedom-adblock.")
    }

    func testWrongSignerRejected() async throws {
        let recorder = Recorder()
        var io = makeIO(recorder: recorder)
        io.sigAddress = "0x0000000000000000000000000000000000000001"
        let service = makeService(io: io)

        let outcome = await service.runOnce()

        guard case .failed(let reason) = outcome else { return XCTFail("expected .failed, got \(outcome)") }
        XCTAssertTrue(reason.contains("signerMismatch"), reason)
        XCTAssertTrue(recorder.downloadedRefs.isEmpty, "nothing downloaded for a bad manifest")
    }

    func testFeedUnavailableDoesNotStampLastCheck() async throws {
        let recorder = Recorder()
        var io = makeIO(recorder: recorder)
        io.readFeed = { throw BeeAPIClient.Error.notRunning }
        let service = makeService(io: io)

        let outcome = await service.runOnce()

        guard case .feedUnavailable = outcome else { return XCTFail("expected .feedUnavailable, got \(outcome)") }
        XCTAssertEqual(UserDefaults.standard.double(forKey: "adblock.update.lastCheck"), 0,
                       "a node-not-up launch must not burn the 6h window")
    }

    func testDisabledWithoutTrustAnchor() async throws {
        let recorder = Recorder()
        var io = makeIO(recorder: recorder)
        io.trustConfigured = false
        let service = makeService(io: io)

        let outcome = await service.runOnce()
        XCTAssertEqual(outcome, .disabled)
    }

    // MARK: - Derived metadata

    func testUpdatedMetadataJoinsDesktopSection() throws {
        let payload = Data(fixture.manifestPayload.utf8)
        let manifest = try AdblockUpdateManifest.verify(
            payload: payload, sigAddress: fixture.signerAddress, appliedVersion: nil
        )
        let metadata = AdblockUpdateService.updatedMetadata(from: manifest)

        XCTAssertEqual(metadata.categories.map(\.id), ["easylist", "easyprivacy"])
        let easylist = metadata.categories[0]
        XCTAssertEqual(easylist.listTitle, "EasyList")
        XCTAssertEqual(easylist.sourceUrl, "https://easylist.to/easylist/easylist.txt")
        XCTAssertEqual(easylist.outputRuleCount, 2, "sum of shard rule counts")
        XCTAssertEqual(easylist.shards.map(\.filename), ["easylist-1.json", "easylist-2.json"])
        XCTAssertEqual(metadata.libVersion, "adblock_rs@0.12.3")
    }
}
