import Foundation

/// The open-source inventory bundled as `licenses.json` — every
/// component that ships inside the app: the native components in
/// FreedomMobile.xcframework, the Rust crates they link, the Swift
/// packages, and the ad-blocking filter lists. Regenerated by
/// `scripts/licenses/generate.py`; `LicensesTests` fails when it drifts
/// from the pins (desktop `NOTICES` + `licenses-audit.test.js` parity).
struct LicenseInventory: Decodable {
    struct App: Decodable {
        let name: String
        let url: String
        let license: String
    }

    struct Entry: Decodable, Identifiable, Hashable {
        let id: String
        let name: String
        let version: String
        /// SPDX expression, or a short description when no id fits.
        let license: String
        let url: String?
        let sourceURL: String?
        let copyright: String?
        /// Apache-2.0 §4(d) NOTICE, reproduced verbatim.
        let notice: String?
        let note: String?
        /// Keys into `texts`; empty → the SPDX texts the expression names.
        let textIDs: [String]?
    }

    let generated: String
    /// The FreedomMobile tag the Rust inventory was derived from.
    let ffiTag: String
    let app: App
    let components: [Entry]
    let swiftPackages: [Entry]
    let rustCrates: [Entry]
    let filterLists: [Entry]
    /// SPDX id → key into `texts`.
    let spdxTexts: [String: String]
    let texts: [String: String]

    enum Error: Swift.Error { case missingResource }

    static func load(bundle: Bundle = .main) throws -> LicenseInventory {
        guard let url = bundle.url(forResource: "licenses", withExtension: "json") else { throw Error.missingResource }
        return try JSONDecoder().decode(LicenseInventory.self, from: Data(contentsOf: url))
    }

    /// Parsed once; the file is a quarter megabyte.
    static let shared: LicenseInventory? = try? load()

    var all: [Entry] { components + filterLists + swiftPackages + rustCrates }

    func entry(id: String) -> Entry? { all.first { $0.id == id } }

    /// The licence texts to show for an entry: its own files when the
    /// inventory carries them, else the SPDX texts its expression names.
    func texts(for entry: Entry) -> [(title: String, text: String)] {
        if let ids = entry.textIDs, !ids.isEmpty {
            return ids.compactMap { id in texts[id].map { (title: Self.title(of: $0), text: $0) } }
        }
        return Self.spdxIDs(in: entry.license).compactMap { id in
            spdxTexts[id].flatMap { texts[$0] }.map { (title: id, text: $0) }
        }
    }

    /// The SPDX ids in an expression such as `MIT OR Apache-2.0`.
    static func spdxIDs(in expression: String) -> [String] {
        var seen = Set<String>()
        return expression
            .split(whereSeparator: { "()/ \t".contains($0) })
            .map(String.init)
            .filter { !["OR", "AND", "WITH"].contains($0) && seen.insert($0).inserted }
    }

    private static func title(of text: String) -> String {
        text.split(separator: "\n").map { $0.trimmingCharacters(in: .whitespaces) }.first(where: { !$0.isEmpty }) ?? "Licence"
    }
}
